name: 📦 Create Marketing SDK Release

on:
  push:
    # paths:
    #   - 'spec/marketing.json'
    #   - 'swagger-config/marketing/**.*'
    #   - '.github/workflows/create-release-marketing.yml'
    branches:
      - disabled

env:
  PUBLISH_INTERNAL: false # whether or not to push to git repos
  PUBLISH_EXTERNAL: false # whether or not to push to package managers

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: NPM Install
        run: npm install
      - name: Validate Marketing Spec
        run: npx @apidevtools/swagger-cli validate spec/marketing.json
      - name: Set Version
        id: set-version
        run: node utils/actions/setVersionVar.js --api=marketing

  setup-cache:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir
      - name: Install Codegen CLI
        if: steps.init-cache-mc.outputs.cache-hit != 'true'
        run: |
          mkdir .cache
          wget https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.7/swagger-codegen-cli-2.4.7.jar -O .cache/swagger-codegen-cli.jar
          java -jar .cache/swagger-codegen-cli.jar help

  generate-node:
    runs-on: ubuntu-latest
    needs: [validate, setup-cache]
    steps:
      - uses: actions/checkout@v2

      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@mailchimp'

      - name: Generate → marketing-javascript
        run: |
          npm install
          node utils/actions/updateLangConfig.js --api=marketing --lang=javascript --specVersion=${{ env.SPEC_VERSION }}
          npm run generate:javascript:marketing
          node utils/actions/generateTypes.js --api=marketing
        env:
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      - name: Rename marketing-javascript → marketing-node
        working-directory: swagger-out
        run: |
          mv marketing-javascript marketing-node

      - name: Zip build artifact → marketing-node
        working-directory: swagger-out/marketing-node
        run: zip -r mailchimp-marketing-node.zip .

      - name: Upload build artifact → marketing-node
        uses: actions/upload-artifact@v1
        with:
          name: mailchimp-marketing-node.zip
          path: swagger-out/marketing-node/mailchimp-marketing-node.zip

  generate-php:
    runs-on: ubuntu-latest
    needs: [validate, setup-cache]

    steps:
      - uses: actions/checkout@v2
      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Generate → marketing-php
        run: |
          npm install
          node utils/actions/updateLangConfig.js --api=marketing --lang=php --specVersion=${{ env.SPEC_VERSION }}
          npm run generate:php:marketing
        env:
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      - name: Zip build artifact → marketing-php
        working-directory: swagger-out/marketing-php
        run: zip -r mailchimp-marketing-php.zip .

      - name: Upload build artifact → marketing-php
        uses: actions/upload-artifact@v1
        with:
          name: mailchimp-marketing-php.zip
          path: swagger-out/marketing-php/mailchimp-marketing-php.zip

  generate-ruby:
    runs-on: ubuntu-latest
    needs: [validate, setup-cache]
    steps:
      - uses: actions/checkout@v2

      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Generate → marketing-ruby
        run: |
          npm install
          node utils/actions/updateLangConfig.js --api=marketing --lang=ruby --specVersion=${{ env.SPEC_VERSION }}
          npm run generate:ruby:marketing
        env:
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      - name: Zip build artifact → marketing-ruby
        working-directory: swagger-out/marketing-ruby
        run: zip -r mailchimp-marketing-ruby.zip .

      - name: Upload build artifact → marketing-ruby
        uses: actions/upload-artifact@v1
        with:
          name: mailchimp-marketing-ruby.zip
          path: swagger-out/marketing-ruby/mailchimp-marketing-ruby.zip

  generate-python:
    runs-on: ubuntu-latest
    needs: [validate, setup-cache]
    steps:
      - uses: actions/checkout@v2

      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Generate → marketing-python
        run: |
          npm install
          node utils/actions/updateLangConfig.js --api=marketing --lang=python --specVersion=${{ env.SPEC_VERSION }}
          npm run generate:python:marketing
        env:
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      - name: Zip build artifact → marketing-python
        working-directory: swagger-out/marketing-python
        run: zip -r mailchimp-marketing-python.zip .

      - name: Upload build artifact → marketing-python
        uses: actions/upload-artifact@v1
        with:
          name: mailchimp-marketing-python.zip
          path: swagger-out/marketing-python/mailchimp-marketing-python.zip

  create-release:
    runs-on: ubuntu-latest
    needs:
      [validate, generate-node, generate-php, generate-ruby, generate-python]
    steps:
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SPEC_VERSION: ${{ needs.validate.outputs.version }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Mailchimp Marketing v${{ env.SPEC_VERSION }}
          draft: true
          prerelease: false

  publish-node:
    runs-on: ubuntu-latest
    needs: [validate, create-release]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@mailchimp'

      - name: Prepare Build & Publishing Tools
        run: npm install

      - uses: actions/download-artifact@v1
        with:
          name: mailchimp-marketing-node.zip
          path: zip

      - name: Unzip build artifact
        run: |
          unzip zip/mailchimp-marketing-node.zip -d marketing-node

      - name: Publish → internal → marketing-node
        if: env.PUBLISH_INTERNAL == 'true'
        working-directory: marketing-node
        run: |
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://github:"$GITHUB_TOKEN"@github.com/mailchimp/mailchimp-marketing-node.git
          git add --force .
          git commit -m "Update mailchimp-marketing-node to v${{ env.SPEC_VERSION }}"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      - name: Publish → npm → marketing-node
        if: env.PUBLISH_EXTERNAL == 'true'
        working-directory: marketing-node
        run: |
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-php:
    runs-on: ubuntu-latest
    needs: [validate, create-release]
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - uses: actions/download-artifact@v1
        with:
          name: mailchimp-marketing-php.zip
          path: zip

      - name: Unzip build artifact
        run: |
          unzip zip/mailchimp-marketing-php.zip -d marketing-php

      - name: Publish → internal → marketing-php
        if: env.PUBLISH_INTERNAL == 'true'
        working-directory: marketing-php/MailchimpMarketing
        run: |
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://github:"$GITHUB_TOKEN"@github.com/mailchimp/mailchimp-marketing-php.git
          git add --force .
          git commit -m "Update mailchimp-marketing-php to v${{ env.SPEC_VERSION }}"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

  publish-ruby:
    runs-on: ubuntu-latest
    needs: [validate, create-release]
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - name: Install Ruby 2.6.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Prepare Build & Publishing Tools
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_TOKEN}\n" > $HOME/.gem/credentials
        env:
          RUBYGEMS_TOKEN: ${{ secrets.RUBYGEMS_TOKEN }}

      - uses: actions/download-artifact@v1
        with:
          name: mailchimp-marketing-ruby.zip
          path: zip

      - name: Unzip build artifact
        run: |
          unzip zip/mailchimp-marketing-ruby.zip -d marketing-ruby

      - name: Publish → internal → marketing-ruby
        if: env.PUBLISH_INTERNAL == 'true'
        working-directory: marketing-ruby
        run: |
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://github:"$GITHUB_TOKEN"@github.com/mailchimp/mailchimp-marketing-ruby.git
          git add --force .
          git commit -m "Update mailchimp-marketing-ruby to v${{ env.SPEC_VERSION }}"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      - name: Publish → RubyGems → marketing-ruby
        if: env.PUBLISH_EXTERNAL == 'true'
        run: |
          gem build marketing-ruby/*.gemspec
          gem push marketing-ruby/*.gem -k rubygems

  publish-python:
    runs-on: ubuntu-latest
    needs: [validate, create-release]
    steps:
      - uses: actions/checkout@v2
      - name: Initialize Marketing Cache
        id: init-cache-mc
        uses: actions/cache@v1
        with:
          path: .cache
          key: cache-dir

      - name: Install Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/download-artifact@v1
        with:
          name: mailchimp-marketing-python.zip
          path: zip

      - name: Unzip build artifact
        run: |
          unzip zip/mailchimp-marketing-python.zip -d marketing-python

      - name: Prepare Build & Publishing Tools
        working-directory: marketing-python
        run: |
          python -m pip install --user setuptools wheel --no-warn-script-location
          python setup.py bdist_wheel

      - name: Publish → internal → marketing-python
        if: env.PUBLISH_INTERNAL == 'true'
        working-directory: marketing-python
        run: |
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote add origin https://github:"$GITHUB_TOKEN"@github.com/mailchimp/mailchimp-marketing-python.git
          git add --force .
          git commit -m "Update mailchimp-marketing-python to v${{ env.SPEC_VERSION }}"
          git push origin master --force
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          SPEC_VERSION: ${{ needs.validate.outputs.version }}

      # Publish Marketing SDKs Externally
      - name: Publish → PyPI → marketing-python (test)
        if: env.PUBLISH_EXTERNAL == 'true'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN_TEST }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: marketing-python/dist

      - name: Publish → PyPI → marketing-python (dist)
        if: env.PUBLISH_EXTERNAL == 'true'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: marketing-python/dist
